# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-28 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uphone',
            field=models.IntegerField(),
        ),
    ]
