# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-28 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20180328_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='alive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='uname',
            field=models.CharField(default='匿名', max_length=30),
        ),
    ]
