# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-28 01:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20180328_0941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='alive',
            new_name='isAlive',
        ),
    ]
