# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-01 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20180401_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodstype',
            name='description',
            field=models.TextField(null=True, verbose_name='类别描述'),
        ),
        migrations.AlterField(
            model_name='goodstype',
            name='picture',
            field=models.ImageField(upload_to='static/upload/goodsType', verbose_name='类别图片'),
        ),
        migrations.AlterField(
            model_name='goodstype',
            name='title',
            field=models.CharField(max_length=30, verbose_name='商品类别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='isAlive',
            field=models.BooleanField(default=True, verbose_name='用户状态'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=15, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uname',
            field=models.CharField(default='匿名', max_length=30, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uphone',
            field=models.CharField(max_length=11, verbose_name='手机号'),
        ),
    ]
